language: c
compiler:
  - gcc
  - clang
before_install:
  - "sudo apt-get install debhelper, intltool, pkg-config, libgtk2.0-dev, libnotify-dev"
  - "sudo apt-get install libunique-dev, libgstreamer1.0-dev"
script: ./autogen.sh
