language: c
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
before_install:
  - sudo apt-get update

install:
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y debhelper intltool pkg-config libgtk2.0-dev libnotify-dev
  - sudo apt-get install -y libunique-dev libgstreamer1.0-dev
script:
  - ./autogen.sh
  - make
