language: c
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
before_install:
  - "sudo apt-get install debhelper, intltool, pkg-config, libgtk2.0-dev, libnotify-dev"
  - "sudo apt-get install libunique-dev, libgstreamer1.0-dev"
script: ./autogen.sh
